FROM balenalib/%%BALENA_MACHINE_NAME%%-debian

RUN apt-get update && apt-get install -y curl wget build-essential libelf-dev awscli bc flex libssl-dev python bison git
COPY . /usr/src/app
WORKDIR /usr/src/app

RUN git clone https://github.com/balena-io-playground/hardlockup.git

ENV VERSION '2.38.0+rev1.dev'
RUN ./build.sh %%BALENA_MACHINE_NAME%% $VERSION hardlockup

CMD ["sleep", "infinity"]
